services:
  educationcontentservice.core:
    image: ${DOCKER_REGISTRY-}educationcontentservicecore
    build:
      context: .
      dockerfile: EducationContentService.Core/Dockerfile
  educationcontent.seq:
    container_name: educationcontent-seq
    image: datalust/seq:latest    
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_FIRSTRUN_NOAUTHENTICATION: 'true'
    ports:
      - "5342:5341"
      - "8081:80"
