services:
  educationcontentservice.core:
    image: ${DOCKER_REGISTRY-}educationcontentservicecore
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: EducationContentService.Core/Dockerfile
  educationcontent.seq:
    container_name: educationcontent-seq
    image: datalust/seq:latest    
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_FIRSTRUN_NOAUTHENTICATION: 'true'
    ports:
      - "5342:5341"
      - "8081:80"
  educationcontent.postgres:
    image: postgres:17.6
    container_name: educationcontent-postgres
    environment:
      POSTGRES_DB: education-service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - educationcontent.postgres