services:
  educationcontentservice.core:
    image: ${DOCKER_REGISTRY-}educationcontentservicecore
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: EducationContentService.Core/Dockerfile
    depends_on:
      - educationcontent.postgres
      - educationcontent.seq
    networks:
      - education-network

  educationcontent.seq:
    container_name: educationcontent-seq
    image: datalust/seq:latest    
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_FIRSTRUN_NOAUTHENTICATION: 'true'
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq-data:/data
    networks:
      - education-network

  educationcontent.postgres:
    image: postgres:17.2
    container_name: educationcontent-postgres
    environment:
      POSTGRES_DB: education-service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - education-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - educationcontent.postgres
    networks:
      - education-network

volumes:
  postgres-data:
  seq-data:
  pgadmin-data:

networks:
  education-network:
    driver: bridge